### OBTENIENDO STORES
GET http://localhost:8083/country
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJjYXJsb3NAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImlkIjo2MDAsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiI0YTlhNmYyMS1mZTdjLTQ5ZDctODNkMy04MzVmMDE3OWVhYmUiLCJlbWFpbCI6ImNhcmxvc0BnbWFpbC5jb20iLCJjbGllbnRfaWQiOiJzYWtpbGEifQ.Xgg48Y7aYhlJgyrKl6RN25S7clMdAM9-wJP4h1J4HDQ
###