###OBTENER TODOS LOS FILMS
GET http://localhost:8083/film?country_id=8&page=0&query=ACADEMY&actor=PENELOPE
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJjYXJsb3NAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImlkIjo2MDAsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiIzN2U3ZjkwMi1lNzg5LTQzYzEtYTEzMS0zMTE0ZTQ5MDc0MTUiLCJlbWFpbCI6ImNhcmxvc0BnbWFpbC5jb20iLCJjbGllbnRfaWQiOiJzYWtpbGEifQ.EZ7LsmGtcGaB3k0_4PoCtpnqgA0vK1_kz6HrHWhtU_0

###LO MAS RENTADO SEGUN FECHA (SE ENVIA FECHA)

GET http://localhost:8083/film/most-rented?country_id=8&page=0&date=2021-11-20
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJjYXJsb3NAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImlkIjo2MDAsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiIzN2U3ZjkwMi1lNzg5LTQzYzEtYTEzMS0zMTE0ZTQ5MDc0MTUiLCJlbWFpbCI6ImNhcmxvc0BnbWFpbC5jb20iLCJjbGllbnRfaWQiOiJzYWtpbGEifQ.EZ7LsmGtcGaB3k0_4PoCtpnqgA0vK1_kz6HrHWhtU_0

###PARA RENTAR PELICULAS PRUEBA 1 Y 2

POST http://localhost:8083/film/rent?country_id=8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJjYXJsb3NAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImlkIjo2MDAsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiIzN2U3ZjkwMi1lNzg5LTQzYzEtYTEzMS0zMTE0ZTQ5MDc0MTUiLCJlbWFpbCI6ImNhcmxvc0BnbWFpbC5jb20iLCJjbGllbnRfaWQiOiJzYWtpbGEifQ.EZ7LsmGtcGaB3k0_4PoCtpnqgA0vK1_kz6HrHWhtU_0

{
  "filmIds": [1,2]
}