###OBTENER TODOS LOS FILMS // EN TODOS LOS ENDPOINTS SE PONE EL ID DEL COUNTRY >:V
###ULTIMAS 10 PELICULAS INCORPORADAS AL CATALOGO
GET http://localhost:8083/film?country_id=8&page=0
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJjYXJsb3NAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImlkIjo2MDAsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiI0YTlhNmYyMS1mZTdjLTQ5ZDctODNkMy04MzVmMDE3OWVhYmUiLCJlbWFpbCI6ImNhcmxvc0BnbWFpbC5jb20iLCJjbGllbnRfaWQiOiJzYWtpbGEifQ.Xgg48Y7aYhlJgyrKl6RN25S7clMdAM9-wJP4h1J4HDQ



###OBTENER el FILM POR NOMBRE PELICULA Y ACTOR
GET http://localhost:8083/film?country_id=8&page=0&query=ACADEMY&actor=PENELOPE
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJjYXJsb3NAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImlkIjo2MDAsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiI0YTlhNmYyMS1mZTdjLTQ5ZDctODNkMy04MzVmMDE3OWVhYmUiLCJlbWFpbCI6ImNhcmxvc0BnbWFpbC5jb20iLCJjbGllbnRfaWQiOiJzYWtpbGEifQ.Xgg48Y7aYhlJgyrKl6RN25S7clMdAM9-wJP4h1J4HDQ

###OBTENER FILM POR NOMBRE
GET http://localhost:8083/film?country_id=8&page=0&query=ACADEMY
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJjYXJsb3NAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImlkIjo2MDAsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiI0YTlhNmYyMS1mZTdjLTQ5ZDctODNkMy04MzVmMDE3OWVhYmUiLCJlbWFpbCI6ImNhcmxvc0BnbWFpbC5jb20iLCJjbGllbnRfaWQiOiJzYWtpbGEifQ.Xgg48Y7aYhlJgyrKl6RN25S7clMdAM9-wJP4h1J4HDQ

###OBTENER FILM POR ACTOR
GET http://localhost:8083/film?country_id=8&page=0&actor=PENELOPE
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJjYXJsb3NAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImlkIjo2MDAsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiI0YTlhNmYyMS1mZTdjLTQ5ZDctODNkMy04MzVmMDE3OWVhYmUiLCJlbWFpbCI6ImNhcmxvc0BnbWFpbC5jb20iLCJjbGllbnRfaWQiOiJzYWtpbGEifQ.Xgg48Y7aYhlJgyrKl6RN25S7clMdAM9-wJP4h1J4HDQ



###OBTENER PELICULAS POR LO MAS RENTADO SEGUN FECHA (SE ENVIA FECHA)
GET http://localhost:8083/film/most-rented?country_id=20&page=0
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJjYXJsb3NAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImlkIjo2MDAsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiI0YTlhNmYyMS1mZTdjLTQ5ZDctODNkMy04MzVmMDE3OWVhYmUiLCJlbWFpbCI6ImNhcmxvc0BnbWFpbC5jb20iLCJjbGllbnRfaWQiOiJzYWtpbGEifQ.Xgg48Y7aYhlJgyrKl6RN25S7clMdAM9-wJP4h1J4HDQ

###PARA RENTAR PELICULAS PRUEBA 1 Y 2

POST http://localhost:8083/film/rent?country_id=8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJjYXJsb3NAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImlkIjo2MDAsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiI0YTlhNmYyMS1mZTdjLTQ5ZDctODNkMy04MzVmMDE3OWVhYmUiLCJlbWFpbCI6ImNhcmxvc0BnbWFpbC5jb20iLCJjbGllbnRfaWQiOiJzYWtpbGEifQ.Xgg48Y7aYhlJgyrKl6RN25S7clMdAM9-wJP4h1J4HDQ

{
  "filmIds": [1]
}